### PR TITLE
Improving core.UID_PROPERTY uniqueness.

### PR DESCRIPTION
**Pull request by henvic**
I have made some tests to see how bad it was: https://gist.github.com/henvic/409bd08bf28cba38a862

And it doesn't seem 'that' bad for our needs, but here is a patch anyways.

https://medium.com/@betable/tifu-by-using-math-random-f1c308c4fd9d
8eb7270

### CODE REVIEW

**Comment by mairatma** [comment]
Nice, makes sense that this is even better. Do you have the results for this same test when run with your change?

@eduardolundgren, can you take a look and confirm that this small change is all right?

**Comment by henvic** [comment]
0 duplicates, as expected.

**Comment by eduardolundgren** [comment]
This should be fine, if it's clear what it does.

@henvic Could you explain why the modulus operation on Date.now() % 1e9?

**Comment by henvic** [comment]
The first digits of Date.now() are always the same during a given decade / year / month / etc, so by taking the modulus we just get rid of most part of the id that doesn't add uniqueness. We lose the side-effect of knowing for certainly when the id was created with easiness, but it really doesn't really matter for any practical reason.

**Comment by eduardolundgren** [comment]
LGTM. Thanks for the change!

**Comment by mairatma** [comment]
Thanks! Pull request merged :)

**Pull request closed without merging**
