### PR TITLE
Making the async module Node compatible.

### PR DESCRIPTION
**Pull request by henvic**

### CODE REVIEW

**Comment by henvic** [comment]
Comments added.

**Comment by yuchi** [comment]
I think the correct change would be to use `global.…` instead of `window.…`. In fact `core.isFunction` just uses `typeof`.

Is the build system of Metal polyfilling `global`?

**Comment by mairatma** [comment]
@yuchi, we actually want api.js to work both on browsers and on node, but using `global....` would only work on node, unless we polyfill it like you mentioned. I'd personally prefer changing the check this way to adding a `window.global` variable, though both approaches are fine.

**Comment by henvic** [comment]
@yuchi, you need to use the typeof operator directly here, because if you try to use it inside a function enclosing it (as in core.isFunction) when an undefined variable is passed to the function an exception will be thrown. If we use directly we will get back the undefined value.

**Comment by yuchi** [comment]
@mairatma: I'm not specifically advocating for placing it as `window.global` 😬 both Webpack and Browserify shim it automatically with a local reference.

@henvic that's for sure :)

**Comment by mairatma** [comment]
You're right, we could add it as a local variable for each file as well during the build, but that would make the build more complicated. We prefer leaving the code like this, which would work regardless of how the files are built.

**Comment by yuchi** [comment]
I just wanted to point that while no real standard way to get globals exists, the `global.…` form is way more explicit and… cool! :sunglasses:

**Comment by henvic** [comment]
@mairatma, I have added a more detailed comment.

**Comment by mairatma** [comment]
Thanks @henvic! Just remember to run `gulp lint` next time, there was a small lint error which I've fixed.
I'll see if I can setup github to automatically run this for each pr later, but for now it's manual :)

**Pull request merged**
