### PR TITLE
Adds Karma Firefox Launcher

### PR DESCRIPTION
**Pull request by fernandosouza**
I think it's useful for detecting FF issues before sending to CI.

### CODE REVIEW

**Comment by mairatma** [comment]
Doesn't that work by just running `gulp test:browsers` today? The idea is to have a fast test in `gulp test` on a single browser so you can focus on logic mistakes, and then you can run `gulp test:browsers` to check if there are any browser specific problems. The IE browsers for this command are a bit problematic (probably due to the need of having the right virtual machines installed on Mac) but the others like Firefox and Safari should be working as expected.

**Comment by fernandosouza** [comment]
I did not notice that `gulp test:browsers` could do what I would like. It was useful to me because I could check out only these two browsers because they were the counterpoint of my problem, or, only set FF for a specific debug.

:)

**Comment by mairatma** [comment]
I think it's best to keep this as is then: one command to run in a single browser for fast testing, and another for running in all browsers. Whenever you need to run a specific different browser you can set it up temporarily on your side. It's more work but it's a rarer use case :)

**Comment by fernandosouza** [comment]
Perfect! :)

**Pull request closed without merging**
